name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote 
        env:
          mlops: ${{ secrets.mlops }}
        run: git remote add space https://umairzia1773:$mlops@huggingface.co/spaces/umairzia1773/mlops
      - name: Push to hub
        env:
          mlops: ${{ secrets.mlops }}
        run: git push --force https://umairzia1773:$mlops@huggingface.co/spaces/umairzia1773/mlops main
